### PR TITLE
It will be combination of ClosestCity and Region but I experience som…

### PR DESCRIPTION
**Pull request by kermit10000000**
…e weird compilator problems:

Maybe you will know: Region.cpp:(.text+0x5108): undefined reference to `std::experimental::filesystem::v1::__cxx11::path::_M_split_cmpts()'
Region.cpp:(.text+0x512a): undefined reference to `DatabaseReader::readCitiesFromFile(std::experimental::filesystem::v1::__cxx11::path const&)'
Region.cpp:(.text+0x52b3): undefined reference to `ClosestCity::getAllBiggestCitiesInOrder(std::vector<City, std::allocator<City> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'

Signed-off-by: Wojciech Mielczarek <kermit10000000@gmail.com>

### CODE REVIEW

**Review by JaroslawWiosna — APPROVED** [review]
You need `-lstdc++fs` in `COMPILE_FLAGS`

**Comment by kermit10000000** [comment]
The given flag is not working. I have tried in many different orders etc. but the problem still occurs. I assume that since I did not have this problem before in the main it is caused by the presence of library in the Region class or the way we call things in the function(?). Anyway I do not know the solution so far and I can not find any working advice on the internet.

**Comment by kermit10000000** [comment]
Combination of ClosestCity and Region. Moved to main.cpp as it is not compiling in the Region class in where it tries to use the #include <experimental/filesystem> from unknown reason.

**Comment by JaroslawWiosna** [comment]
https://stackoverflow.com/a/45332844

Anyways, we have some trouble with this `fs`. It won't compile even with this `c++experimental` linker flag.
I think that we should get back to `std::string` instead of `std::experimental::filesystem`
If clang is not happy about `std::experimental::filesystem` then it is the only solution.

**Comment by kermit10000000** [comment]
Ok. So I will deliver this change now and later when we remove this as you said I will retry on making it in class Region.

**Pull request merged**
