### PR TITLE
Unit database

### PR DESCRIPTION
**Pull request by kermit10000000**
New splendid unittests for Flag Parser
Adding support for travis for more bug logs. If the test fails we will see a nice assert message.
Example of failed logs:
obraz

### CODE REVIEW

**Comment by kermit10000000** [comment]
well yeah quite weird that we have some old commits but probably it is because we had a lot of changes etc lastly or smth. also we have to lower the number of branches as we have 7 now.

**Comment by kermit10000000** [comment]
hmm, wait i have to see why travis did not make more logs.

**Comment by kermit10000000** [comment]
amazing hackv2 worked

**Comment by kermit10000000** [comment]
Also question should we add a flag to also continue check after assert fail? There are both prons and cons of that so it is tricky issue. Maybe check more but also previous error might cause further errors.

**Review by JaroslawWiosna — COMMENTED** [review]
Splendid, indeed, is your work, my friend.

**Review by JaroslawWiosna — APPROVED** [review]
Merge it, now!

**Pull request merged**
