### PR TITLE
 Progress Bar unittest 

### PR DESCRIPTION
**Pull request by JaroslawWiosna**

### CODE REVIEW

**Comment by kermit10000000** [comment]
wow 100 commit ^_^ we should celebrate. btw. assert true(true) ?

**Comment by JaroslawWiosna** [comment]
@kermit10000000 Unfortunately, this is not working. please, have a look in travis job.

**Comment by kermit10000000** [comment]
should we create issue for this bug?

**Comment by JaroslawWiosna** [comment]
@kermit10000000 Yeah... I think so, please, do it.

**Comment by kermit10000000** [comment]
any progress?

**Comment by JaroslawWiosna** [comment]
I just do not know what is going on with travis.

**Comment by kermit10000000** [comment]
maybe add comments like me in the unit test to see exacly in which place it fails or something?

**Comment by JaroslawWiosna** [comment]
Let's merge it to the baseline.
We can improve unittesting for `ProgressBar` in a separate pull request, what do you thinh, @kermit10000000  ?

**Comment by kermit10000000** [comment]
Yeah we can have a basic test for now yet this unittests should be applied in the nearest future to fully test the class

**Pull request merged**
