### PR TITLE
it will prevent from further bugs in case of additional whitespaces in the database

### LINKED ISSUE #18: remove heading and trailing spaces in tokens in `split` function
[split](https://github.com/JaroslawWiosna/regionalizer/blob/master/DatabaseReader)/DatabaseReader.cpp#L34 : 
```c++
void split (std::string str, std::string splitBy, std::vector<std::string>& tokens) {
    tokens.push_back(str);
    std::size_t splitAt;
    std::size_t splitLen = splitBy.size();
    std::string frag;
    while (true) {
        frag = tokens.back();
	splitAt = frag.find(splitBy);
	if (splitAt == std::string::npos) {
            break;
        }
	tokens.back() = frag.substr(0, splitAt);
	tokens.push_back(frag.substr(splitAt+splitLen, frag.size()-(splitAt+splitLen)));
    }
}
```
This is an outstanding algorithm, but let's have a look below:
```sh
[osboxes@osboxes build]$ gdb ./regionalizer
GNU gdb (GDB) 8.0.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./regionalizer...done.
(gdb) set args -list ../database/Poland-Cities010-Top10-mock.txt 
(gdb) show args
Argument list to give program being debugged when it is started is "-list ../database/Poland-Cities010-Top10-mock.txt ".
(gdb) break main.cpp:28
Breakpoint 1 at 0x22ce8: file /home/osboxes/github/regionalizer/main.cpp, line 28.
(gdb) run
Starting program: /home/osboxes/github/regionalizer/build/regionalizer -list ../database/Poland-Cities010-Top10-mock.txt 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
printFlags
-list ../database/Poland-Cities010-Top10-mock.txt
Great! ../database/Poland-Cities010-Top10-mock.txt is being processed

Breakpoint 1, main (argc=3, argv=0x7fffffffe698) at /home/osboxes/github/regionalizer/main.cpp:28
28          for (City i : vec) {
(gdb) print i
$1 = {name = "`\033|UUU\000\000ase/Poland-Cities010-Top10-mock.txt", area = 93824994593800, population = 93824992457192, latitude = <error: Cannot access memory at address 0x32>, longitude = <error: Cannot access memory at address 0xd>, 
  distanceToTheFarthest = 93824992465568}
(gdb) n
29              std::cout << i.getAllFields();
(gdb) print i
$2 = {name = "Warsaw ", area = 517, population = 1702139, latitude = " 52.23 ", longitude = " 21.012", distanceToTheFarthest = 0}
(gdb) 
```

I am talking about the very last line:
```
name = "Warsaw "
```
...and there is **a trailing space** in `name` field.
It looks bad and may cause unpleasant issues in the future.

### PR DESCRIPTION
**Pull request by kermit10000000**
it will prevent from further bugs in case of additional whitespaces in the database
Closes #18

Signed-off-by: Wojciech Mielczarek <kermit10000000@gmail.com>

### CODE REVIEW

**Comment by kermit10000000** [comment]
this needs to be merged first https://github.com/JaroslawWiosna/regionalizer/pull/38
Then this change has to be merged with master and delivered

**Review by JaroslawWiosna — CHANGES_REQUESTED** [review]
Are you sure that size_t is enough? Shouldn't it be std::size_t?

please use:
```c++
if (foo) {
    break;
}
```
 1. space between `if` and `(`
 2. new line for `break;`
 3. curly brackets even when there is only one line

**Review by JaroslawWiosna — CHANGES_REQUESTED** [review]
Nice, but 
please, add one space after `while`
add 4 spaces at the begining of each line inserted by you so the indentiation level will be consistent.

**Comment by kermit10000000** [comment]
Kate seems to be a faulty tool(or git?) 
obraz
and what i delivered to git have additional spaces in it so i am not really sure on which level there is a problem

**Review by JaroslawWiosna — APPROVED** [review]

**Pull request merged**
