### PR TITLE
Enable both gcc and clang in travis

### PR DESCRIPTION
**Pull request by JaroslawWiosna**

### CODE REVIEW

**Comment by kermit10000000** [comment]
nice changes but is it clang or clang-format that is being added because the task is for the clang-format?

**Comment by JaroslawWiosna** [comment]
@kermit10000000 it is not about `clang-format`. It is about compiling the code with two compilers:
1. gcc
2. clang (llvm)

**Comment by kermit10000000** [comment]
Oh ok then, I see. Thank you for the answer :)

**Review by kermit10000000 — APPROVED** [review]
Please commit when it will be passing

**Pull request merged**
