### PR TITLE
Files with new formatting based in .clang-format file.

### PR DESCRIPTION
**Pull request by kermit10000000**
Signed-off-by: Wojciech Mielczarek <kermit10000000@gmail.com>

### CODE REVIEW

**Comment by kermit10000000** [comment]
There are two more things (i can add to wiki how to use a clang-format on vim but only if you want to because i don't use or know vim well ) and add clang to travis but i will do it in next commit. This is to be checked for now.

**Comment by kermit10000000** [comment]
I am not really sure what we see as a definion of done in this quest. I would like to add travis but i am not sure how to do this or how long will it take so maybe it should be just another issue. Please tell what you think @JaroslawWiosna

**Comment by kermit10000000** [comment]
Closes #53

**Comment by kermit10000000** [comment]
This is how it might look but i am not sure yet of this solution.. https://github.com/JaroslawWiosna/regionalizer/tree/travis_clang (on new branch to see before decision asked in this commit above)

**Comment by kermit10000000** [comment]
And aboute Readme there is one problem but it makes no sense to me why it did not make a correct linking to clang-format on the beggining

**Review by JaroslawWiosna — COMMENTED** [review]
Looks great!

...but I have two things that I want to talk about:
1. end brace and `else` in the same line:
```c++
if (foo) {
    bar;
}
else {
    baz;
}
```
I thing it would be better like this:
```c++
if (foo) {
    bar;
} else {
    baz;
}
```

2. space after unpersand, NOT before
```c++
std::vector<std::string> &tokens
```
...I think the better option would be:
```c++
std::vector<std::string>& tokens
```

---

Nevertheless, please merge.

**Review by JaroslawWiosna — APPROVED** [review]

**Comment by JaroslawWiosna** [comment]
Let's hold on about travis here.
Firstly, we have to make travis to build both gcc and clang.
I strongly recomend clang-format script in travis to be added in next release

**Comment by kermit10000000** [comment]
Ok I am open to suggestion, I will merge this and prepare the changes proposed (if possible because i am not sure about the second one if we have flag for it) in the new branch .

**Pull request merged**
