### PR TITLE
Code of conduct md.

### LINKED ISSUE #37: Update github files
- [x] update CODE_OF_CONDUCT.md
- [x] update CONTRIBUTING.md
- [x] update ISSUE_TEMPLATE.md

### PR DESCRIPTION
**Pull request by kermit10000000**
Closes #37
Signed-off-by: Wojciech Mielczarek <kermit10000000@gmail.com>

### CODE REVIEW

**Review by JaroslawWiosna — CHANGES_REQUESTED** [review]
Please add 
```
##0 tl;dr
Be a professional 
```
The formatting is bad.
Just have a look [here](https://github.com/JaroslawWiosna/regionalizer/blob/Code_of_conduct/CODE_OF_CONDUCT.md)
Please, check how does it look here: [online markdown editor](http://dillinger.io/) , before submitting changes

**Comment by kermit10000000** [comment]
hmm
the formating of ## did not work. wait with review please

**Comment by JaroslawWiosna** [comment]
Oh, I forgot to write that I'm serious about this:
##0 tl;dr
Be a professional 
I thnk that this one sentence has **it** all.

**Review by JaroslawWiosna — CHANGES_REQUESTED** [review]
What about 
## 0. TL;DR
Be a professional 
?

**Comment by kermit10000000** [comment]
key values are tl;dr...
i remembered you requested it but calling it tl;dr ain't proffesional in official documents

**Comment by kermit10000000** [comment]
If you have your idea of updating this change i think this time you should be the one adding it since i seriously have no idea how the key values should look like differently

**Comment by JaroslawWiosna** [comment]
OK.
So let's refrase it:

```
## 0 Code of conduct in one sentence:
Stay professional 
```

It would be acceptable for you?

**Comment by JaroslawWiosna** [comment]
Is it the `tl;dr` which makes you angry or is it the idea of adding the `##0 section` in general?

**Comment by kermit10000000** [comment]
Is going with this: 2 sections over all tl;dr and the full version a consensus to you : http://www.technottingham.com/code-of-conduct/ ?

**Comment by kermit10000000** [comment]
And if yes should it contain the key values or just your sentence?

**Comment by JaroslawWiosna** [comment]
All right, I think that this patchset is enough for now.
Please, squash and merge it.

---

When it is about `tl;dr` section let's move it to the next release. Maybe next meeting/retrospective/planning is the best time to discuss it. :)

**Review by JaroslawWiosna — APPROVED** [review]

**Comment by JaroslawWiosna** [comment]
@kermit10000000 Please, remember that **after merge** `Code_of_conduct` branch can be safely deleted

**Pull request merged**
