### PR TITLE
Clang-format checking in travis

### PR DESCRIPTION
**Pull request by JaroslawWiosna**

### CODE REVIEW

**Comment by JaroslawWiosna** [comment]
```
(cd .. && exec find regionalizer -iname *.hpp -o -iname *.cpp | xargs clang-format -i -style=file)
```
I am not sure if travis can handle this... `Error reading /home/travis/build/JaroslawWiosna/regionalizer/.clang-format: Invalid argument`

---

`./check_coding_style.sh` exits with 0, which is strage, because there is `lcov` directory. `lcov` is not a part of repo, so the script should always exit with 1. ...but it exits with 0.
In general we want the script to return 0, but this time, when lcov directory exists, scrit should gives us 1.
possible solutions:
1. change `git diff` to `git diff --``
2. use `git status` and check for string: `working directory clean`

**Review by kermit10000000 — APPROVED** [review]
Did you check if it works on commit that was on purpose corrupted? I ask because I do not see the instatlation of files for clang-format so I am not sure if this commands works . And also we can only see it by git status after the -iname *.hpp -o -iname *.cpp | xargs clang-format -i -style=file .
If you are sure and tested that it works like described above please confirm in the comment and merge.

**Comment by JaroslawWiosna** [comment]
@kermit10000000 yes, check 7168760 in https://github.com/JaroslawWiosna/regionalizer/commits/intentionally-made-coding-style-error

**Comment by kermit10000000** [comment]
Ok, then please merge. Thank you for the answer,

**Pull request closed without merging**
